"""Generate NOTICES.md from the dependencies actually in the build.

Written rather than hand-kept, because a hand-kept notice file drifts and a
drifted notice file is worse than none: it states, in writing, that you shipped
something you did not.

    python tools/notices.py           # write NOTICES.md
    python tools/notices.py --check   # fail if NOTICES.md is out of date

Needs `cargo install cargo-license`.
"""

import io
import json
import os
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "NOTICES.md")

# Licences that need more than a line: either they carry a condition worth
# spelling out, or they offer a choice and the choice has to be recorded.
NOTES = {
    "Apache-2.0 OR GPL-2.0": (
        "Offered under either licence. **Apache-2.0 is the one taken here**; "
        "no GPL terms apply to this program."
    ),
    "(Apache-2.0 OR MIT) AND OFL-1.1 AND Ubuntu-font-1.0": (
        "Carries font files under the SIL Open Font Licence and the Ubuntu "
        "Font Licence. They are embedded in the binary as the last-resort "
        "fallback face, so both licences travel with it."
    ),
    "(Apache-2.0 OR MIT) AND BSD-3-Clause": (
        "Includes data tables under BSD-3-Clause; the attribution below covers "
        "them."
    ),
    "(Apache-2.0 OR MIT) AND Unicode-3.0": (
        "Includes Unicode character data under the Unicode licence."
    ),
    "MPL-2.0": (
        "File-level copyleft. It is used unmodified and linked, which the "
        "licence permits in a work under other terms (§ 3.3); what it "
        "requires is that the source of these files stays available, and it is "
        "— unchanged — at the crate's own repository. Modifying them here would "
        "put those files, and only those files, under MPL-2.0."
    ),
    "Apache-2.0 OR LGPL-2.1-or-later OR MIT": (
        "Offered under any of the three. **MIT is the one taken here**; no LGPL "
        "terms apply."
    ),
    "Apache-2.0 OR Apache-2.0 WITH LLVM-exception OR MIT": (
        "Offered under any of the three. **MIT is the one taken here**."
    ),
}

HEADER = """# Notices

Anti-library is distributed under the MIT licence (see `LICENSE`). It is built
on the open source crates listed below, whose licences require that their
copyright notices travel with any copy of this program.

This file is generated by `tools/notices.py` from the crates actually in the
build, so that what it claims and what ships cannot drift apart. `ci.ps1`
re-runs it with `--check`.

## Fonts read from the machine

The reader does **not** redistribute any typeface. It looks for faces already
installed on the computer it runs on — Georgia, Constantia, Times New Roman,
Segoe UI, Tahoma, Segoe MDL2 Assets, Malgun Gothic, Nanum Gothic, DejaVu,
Liberation, Noto, Apple SD Gothic Neo — and falls back to the face embedded in
`epaint_default_fonts` when it finds none. Only that fallback is shipped, and
its licences are listed with the crate below.

## Crates

"""


def main():
    check = "--check" in sys.argv
    proc = subprocess.run(
        ["cargo", "license", "--json"],
        cwd=ROOT,
        capture_output=True,
        text=True,
    )
    if proc.returncode != 0:
        print("cargo license failed — is cargo-license installed?")
        print(proc.stderr.strip()[:2000])
        sys.exit(2)

    crates = json.loads(proc.stdout)
    # The program itself is not a third-party notice.
    crates = [c for c in crates if c.get("name") != "anti-library"]
    by_licence = {}
    for c in crates:
        lic = c.get("license") or "(unstated)"
        by_licence.setdefault(lic, []).append(c["name"])

    lines = [HEADER]
    lines.append("%d crates, under %d licence terms.\n\n" % (len(crates), len(by_licence)))
    for lic in sorted(by_licence, key=lambda l: (-len(by_licence[l]), l)):
        names = sorted(set(by_licence[lic]))
        lines.append("### %s\n\n" % lic)
        if lic in NOTES:
            lines.append("%s\n\n" % NOTES[lic])
        lines.append("%d crate(s): %s\n\n" % (len(names), ", ".join("`%s`" % n for n in names)))

    lines.append(
        "---\n\nThe full text of every one of these licences, with the copyright "
        "notices they carry, is in `THIRD-PARTY-LICENSES.md`, which ships beside "
        "this file. Saying only which licence applies is not what MIT, Apache-2.0, "
        "BSD, the SIL Open Font Licence or the Ubuntu Font Licence ask for — they "
        "ask for the text, and pointing at `~/.cargo/registry/src/` points at a "
        "directory that exists on the machine that built this and nowhere else.\n"
    )
    text = "".join(lines)

    if check:
        current = io.open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != text:
            print("NOTICES.md is out of date — run: python tools/notices.py")
            sys.exit(1)
        print("NOTICES.md matches the %d crates in the build." % len(crates))
        return

    io.open(OUT, "w", encoding="utf-8", newline="").write(text)
    print("NOTICES.md written: %d crates, %d licence terms." % (len(crates), len(by_licence)))


if __name__ == "__main__":
    main()
